### ISSUE TITLE
Verifying proof should not use data from storage

### ISSUE THREAD

**Issue by duanjr** [Nynra/pympt#32]
Merkle proof is designed for Light Node, which will not maintains a full mpt.
Current version will visit storage when verifying proof

**Comment by Nynra** [comment]
That is a very good point, thanks.

**Comment by duanjr** [comment]
I'm now try to understand your code.
In my understanding of MPT, the nodes we visited when we generated proof for a key is exactly the same with those we need when we verify the proof. And I simply return that node list as a proof instead of its hash. This passed small size test but failed bigger size. I suspect current verify function visit unnecessary storage.
I would like to work on this if you are not working on it.

**Comment by Nynra** [comment]
You were right, it was a very sloppy (and wrong) implementation of the merkle-proof, after playing with some code for a normal merkle-tree I think I got the hang of it. 

In the new branch the proof of inclusion is fixed (I think, still have to generate some proofs) but the proof of exclusion is harder to get working. If you could help with one or both that would really help, thanks! The coming few days I don't have time to work on the problem but after that I'll give it another go.

**Comment by Nynra** [comment]
Is fixed
